; Special for Vortex Tracker 2.5, AKG format, v1.0.

; Generated by Arkos Tracker 2.

music__Start
music__StartDisarkGenerateExternalLabel

music__DisarkByteRegionStart0
	db "AT20"
music__DisarkPointerRegionStart1
	dw music__ArpeggioTable	; The address of the Arpeggio table.
	dw music__PitchTable	; The address of the Pitch table.
	dw music__InstrumentTable	; The address of the Instrument table.
	dw music__EffectBlockTable	; The address of the Effect Block table.
music__DisarkPointerRegionEnd1


; The addresses of each Subsong:
music__DisarkPointerRegionStart2
	dw music__Subsong0_Start
music__DisarkPointerRegionEnd2

; Declares all the Arpeggios.
music__ArpeggioTable
music__DisarkPointerRegionStart3
	dw music__Arpeggio1
	dw music__Arpeggio2
	dw music__Arpeggio3
	dw music__Arpeggio4
	dw music__Arpeggio5
music__DisarkPointerRegionEnd3

music__Arpeggio1
	db 1	; The speed.

	db 12
	db 0
	db 3
	db -128
music__DisarkWordForceReference4
	dw music__Arpeggio1 + 0 + 1	; Loop.

music__Arpeggio2
	db 1	; The speed.

	db 12
	db 0
	db 4
	db -128
music__DisarkWordForceReference5
	dw music__Arpeggio2 + 0 + 1	; Loop.

music__Arpeggio3
	db 1	; The speed.

	db 0
	db 3
	db 7
	db -128
music__DisarkWordForceReference6
	dw music__Arpeggio3 + 0 + 1	; Loop.

music__Arpeggio4
	db 1	; The speed.

	db 0
	db 4
	db 7
	db -128
music__DisarkWordForceReference7
	dw music__Arpeggio4 + 0 + 1	; Loop.

music__Arpeggio5
	db 1	; The speed.

	db 0
	db 12
	db 19
	db 0
	db -128
music__DisarkWordForceReference8
	dw music__Arpeggio5 + 0 + 1	; Loop.

; Declares all the Pitches.
music__PitchTable
music__DisarkPointerRegionStart9
music__DisarkPointerRegionEnd9

; Declares all the Instruments.
music__InstrumentTable
music__DisarkPointerRegionStart10
	dw music__EmptyInstrument
	dw music__Instrument1
	dw music__Instrument2
	dw music__Instrument3
	dw music__Instrument4
	dw music__Instrument5
	dw music__Instrument6
	dw music__Instrument7
	dw music__Instrument8
	dw music__Instrument9
music__DisarkPointerRegionEnd10

music__EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
music__EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

music__Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

music__Instrument1_Loop	db 209	; Soft only. Volume: 10. Volume only.

	db 7	; Loop.
music__DisarkWordForceReference11
	dw music__Instrument1_Loop	; Loop here.

music__Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

music__Instrument2_Loop	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -3	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -6	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -3	; Pitch.

	db 217	; Soft only. Volume: 11. Volume only.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 3	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 6	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 3	; Pitch.

	db 217	; Soft only. Volume: 11. Volume only.

	db 7	; Loop.
music__DisarkWordForceReference12
	dw music__Instrument2_Loop	; Loop here.

music__Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 33	; Additional data. Noise: 1. Pitch? true. Arp? false. Period? false.
	dw 384	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 640	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 896	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1152	; Pitch.

music__Instrument3_Loop	db 209	; Soft only. Volume: 10. Volume only.

	db 7	; Loop.
music__DisarkWordForceReference13
	dw music__Instrument3_Loop	; Loop here.

music__Instrument4
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 256	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 512	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 768	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1024	; Pitch.

music__Instrument4_Loop	db 209	; Soft only. Volume: 10. Volume only.

	db 7	; Loop.
music__DisarkWordForceReference14
	dw music__Instrument4_Loop	; Loop here.

music__Instrument5
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 48	; Additional data. Noise: 16. Pitch? true. Arp? false. Period? false.
	dw 128	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 40	; Additional data. Noise: 8. Pitch? true. Arp? false. Period? false.
	dw 256	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 38	; Additional data. Noise: 6. Pitch? true. Arp? false. Period? false.
	dw 384	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 36	; Additional data. Noise: 4. Pitch? true. Arp? false. Period? false.
	dw 512	; Pitch.

music__Instrument5_Loop	db 209	; Soft only. Volume: 10. Volume only.

	db 7	; Loop.
music__DisarkWordForceReference15
	dw music__Instrument5_Loop	; Loop here.

music__Instrument6
	db 1	; The speed (>0, 0 for 256).
	db 105	; Soft only. Volume: 13.
	db 1	; Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

	db 105	; Soft only. Volume: 13.
	db 1	; Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

music__Instrument6_Loop	db 209	; Soft only. Volume: 10. Volume only.

	db 7	; Loop.
music__DisarkWordForceReference16
	dw music__Instrument6_Loop	; Loop here.

music__Instrument7
	db 1	; The speed (>0, 0 for 256).
	db 105	; Soft only. Volume: 13.
	db 33	; Additional data. Noise: 1. Pitch? true. Arp? false. Period? false.
	dw -128	; Pitch.

music__Instrument7_Loop	db 209	; Soft only. Volume: 10. Volume only.

	db 7	; Loop.
music__DisarkWordForceReference17
	dw music__Instrument7_Loop	; Loop here.

music__Instrument8
	db 1	; The speed (>0, 0 for 256).
music__Instrument8_Loop	db 120	; No Soft no Hard. Volume: 15. Noise? false.

	db 7	; Loop.
music__DisarkWordForceReference18
	dw music__Instrument8_Loop	; Loop here.

music__Instrument9
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

music__Instrument9_Loop	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -4	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

	db 217	; Soft only. Volume: 11. Volume only.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 2	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 4	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 2	; Pitch.

	db 217	; Soft only. Volume: 11. Volume only.

	db 7	; Loop.
music__DisarkWordForceReference19
	dw music__Instrument9_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
music__EffectBlockTable
music__DisarkPointerRegionStart20
	dw music__EffectBlock_P4P0	; Index 0
	dw music__EffectBlock_P4P4	; Index 1
	dw music__EffectBlock_P5P0P6P1	; Index 2
	dw music__EffectBlock_P5P0P6P3	; Index 3
	dw music__EffectBlock_P5P0P6P0	; Index 4
	dw music__EffectBlock_P5P0P6P4	; Index 5
	dw music__EffectBlock_P5P0P6P2	; Index 6
	dw music__EffectBlock_P5P1P6P1	; Index 7
	dw music__EffectBlock_P5P1P6P3	; Index 8
	dw music__EffectBlock_P24P64P160P5	; Index 9
	dw music__EffectBlock_P5P2P20P0P7	; Index 10
	dw music__EffectBlock_P5P1P6P0	; Index 11
	dw music__EffectBlock_P5P1P6P2	; Index 12
	dw music__EffectBlock_P24P65P8P7	; Index 13
music__DisarkPointerRegionEnd20

music__EffectBlock_P4P0
	db 4, 0
music__EffectBlock_P4P4
	db 4, 4
music__EffectBlock_P5P0P6P0
	db 5, 0, 6, 0
music__EffectBlock_P5P0P6P1
	db 5, 0, 6, 1
music__EffectBlock_P5P0P6P2
	db 5, 0, 6, 2
music__EffectBlock_P5P0P6P3
	db 5, 0, 6, 3
music__EffectBlock_P5P0P6P4
	db 5, 0, 6, 4
music__EffectBlock_P5P1P6P0
	db 5, 1, 6, 0
music__EffectBlock_P5P1P6P1
	db 5, 1, 6, 1
music__EffectBlock_P5P1P6P2
	db 5, 1, 6, 2
music__EffectBlock_P5P1P6P3
	db 5, 1, 6, 3
music__EffectBlock_P5P2P20P0P7
	db 5, 2, 20, 0, 7
music__EffectBlock_P24P65P8P7
	db 24, 65, 8, 7
music__EffectBlock_P24P64P160P5
	db 24, 64, 160, 5

music__DisarkByteRegionEnd0

; Subsong 0
; ----------------------
music__Subsong0_DisarkByteRegionStart0
music__Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 16	; Loop start index (>=0).
	db 39	; End index (>=0).
	db 3	; Initial speed (>=0).
	db 10	; Base note index (>=0).

music__Subsong0_Linker
music__Subsong0_DisarkPointerRegionStart1
; Position 0
	dw music__Subsong0_Track2
	dw music__Subsong0_Track0
	dw music__Subsong0_Track4
	dw music__Subsong0_LinkerBlock0

; Position 1
	dw music__Subsong0_Track2
	dw music__Subsong0_Track0
	dw music__Subsong0_Track4
	dw music__Subsong0_LinkerBlock0

; Position 2
	dw music__Subsong0_Track5
	dw music__Subsong0_Track0
	dw music__Subsong0_Track7
	dw music__Subsong0_LinkerBlock0

; Position 3
	dw music__Subsong0_Track8
	dw music__Subsong0_Track0
	dw music__Subsong0_Track1
	dw music__Subsong0_LinkerBlock0

; Position 4
	dw music__Subsong0_Track2
	dw music__Subsong0_Track3
	dw music__Subsong0_Track4
	dw music__Subsong0_LinkerBlock0

; Position 5
	dw music__Subsong0_Track2
	dw music__Subsong0_Track3
	dw music__Subsong0_Track4
	dw music__Subsong0_LinkerBlock0

; Position 6
	dw music__Subsong0_Track5
	dw music__Subsong0_Track6
	dw music__Subsong0_Track7
	dw music__Subsong0_LinkerBlock0

; Position 7
	dw music__Subsong0_Track8
	dw music__Subsong0_Track17
	dw music__Subsong0_Track1
	dw music__Subsong0_LinkerBlock0

; Position 8
	dw music__Subsong0_Track9
	dw music__Subsong0_Track3
	dw music__Subsong0_Track10
	dw music__Subsong0_LinkerBlock0

; Position 9
	dw music__Subsong0_Track9
	dw music__Subsong0_Track3
	dw music__Subsong0_Track10
	dw music__Subsong0_LinkerBlock0

; Position 10
	dw music__Subsong0_Track11
	dw music__Subsong0_Track6
	dw music__Subsong0_Track12
	dw music__Subsong0_LinkerBlock0

; Position 11
	dw music__Subsong0_Track13
	dw music__Subsong0_Track17
	dw music__Subsong0_Track18
	dw music__Subsong0_LinkerBlock0

; Position 12
	dw music__Subsong0_Track14
	dw music__Subsong0_Track3
	dw music__Subsong0_Track10
	dw music__Subsong0_LinkerBlock0

; Position 13
	dw music__Subsong0_Track14
	dw music__Subsong0_Track3
	dw music__Subsong0_Track10
	dw music__Subsong0_LinkerBlock0

; Position 14
	dw music__Subsong0_Track15
	dw music__Subsong0_Track6
	dw music__Subsong0_Track12
	dw music__Subsong0_LinkerBlock0

; Position 15
	dw music__Subsong0_Track16
	dw music__Subsong0_Track17
	dw music__Subsong0_Track18
	dw music__Subsong0_LinkerBlock0

; Position 16
music__Subsong0_Linker_Loop
	dw music__Subsong0_Track28
	dw music__Subsong0_Track19
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 17
	dw music__Subsong0_Track28
	dw music__Subsong0_Track19
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 18
	dw music__Subsong0_Track20
	dw music__Subsong0_Track21
	dw music__Subsong0_Track22
	dw music__Subsong0_LinkerBlock0

; Position 19
	dw music__Subsong0_Track23
	dw music__Subsong0_Track24
	dw music__Subsong0_Track25
	dw music__Subsong0_LinkerBlock0

; Position 20
	dw music__Subsong0_Track28
	dw music__Subsong0_Track26
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 21
	dw music__Subsong0_Track28
	dw music__Subsong0_Track29
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 22
	dw music__Subsong0_Track20
	dw music__Subsong0_Track30
	dw music__Subsong0_Track22
	dw music__Subsong0_LinkerBlock0

; Position 23
	dw music__Subsong0_Track23
	dw music__Subsong0_Track31
	dw music__Subsong0_Track25
	dw music__Subsong0_LinkerBlock0

; Position 24
	dw music__Subsong0_Track28
	dw music__Subsong0_Track26
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 25
	dw music__Subsong0_Track28
	dw music__Subsong0_Track29
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 26
	dw music__Subsong0_Track20
	dw music__Subsong0_Track30
	dw music__Subsong0_Track22
	dw music__Subsong0_LinkerBlock0

; Position 27
	dw music__Subsong0_Track23
	dw music__Subsong0_Track31
	dw music__Subsong0_Track25
	dw music__Subsong0_LinkerBlock0

; Position 28
	dw music__Subsong0_Track28
	dw music__Subsong0_Track32
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 29
	dw music__Subsong0_Track28
	dw music__Subsong0_Track32
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 30
	dw music__Subsong0_Track20
	dw music__Subsong0_Track33
	dw music__Subsong0_Track22
	dw music__Subsong0_LinkerBlock0

; Position 31
	dw music__Subsong0_Track23
	dw music__Subsong0_Track34
	dw music__Subsong0_Track25
	dw music__Subsong0_LinkerBlock0

; Position 32
	dw music__Subsong0_Track28
	dw music__Subsong0_Track32
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 33
	dw music__Subsong0_Track28
	dw music__Subsong0_Track32
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 34
	dw music__Subsong0_Track20
	dw music__Subsong0_Track33
	dw music__Subsong0_Track22
	dw music__Subsong0_LinkerBlock0

; Position 35
	dw music__Subsong0_Track23
	dw music__Subsong0_Track34
	dw music__Subsong0_Track25
	dw music__Subsong0_LinkerBlock0

; Position 36
	dw music__Subsong0_Track28
	dw music__Subsong0_Track19
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 37
	dw music__Subsong0_Track28
	dw music__Subsong0_Track19
	dw music__Subsong0_Track27
	dw music__Subsong0_LinkerBlock0

; Position 38
	dw music__Subsong0_Track20
	dw music__Subsong0_Track21
	dw music__Subsong0_Track22
	dw music__Subsong0_LinkerBlock0

; Position 39
	dw music__Subsong0_Track23
	dw music__Subsong0_Track24
	dw music__Subsong0_Track25
	dw music__Subsong0_LinkerBlock0

music__Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
music__Subsong0_DisarkWordForceReference2
	dw music__Subsong0_Linker_Loop

music__Subsong0_LinkerBlock0
	db 32	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
music__Subsong0_DisarkWordForceReference3
	dw music__Subsong0_SpeedTrack0	; SpeedTrack address.
music__Subsong0_DisarkWordForceReference4
	dw music__Subsong0_EventTrack0	; EventTrack address.

music__Subsong0_Track0
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track1
	db 237
	db 1	; New Instrument (1).
	db 8	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track2
	db 239
	db 1	; New Instrument (1).
	db 11	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track3
	db 242
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track4
	db 239
	db 1	; New Instrument (1).
	db 12	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track5
	db 235
	db 1	; New Instrument (1).
	db 7	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track6
	db 239
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track7
	db 235
	db 1	; New Instrument (1).
	db 8	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track8
	db 237
	db 1	; New Instrument (1).
	db 7	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track9
	db 239
	db 3	; New Instrument (3).
	db 4	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 175
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 175
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track10
	db 239
	db 4	; New Instrument (4).
	db 6	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 175
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 175
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track11
	db 235
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 171
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 171
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 171
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track12
	db 235
	db 4	; New Instrument (4).
	db 3	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 171
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 171
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 171
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track13
	db 237
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 173
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 173
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track14
	db 239
	db 3	; New Instrument (3).
	db 4	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 175
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 175
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 175
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 5	; New Instrument (5).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 6	; New Instrument (6).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track15
	db 235
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 171
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 171
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 171
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 171
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 171
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 171
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 5	; New Instrument (5).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 6	; New Instrument (6).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track16
	db 237
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 173
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 173
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 173
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 5	; New Instrument (5).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 6	; New Instrument (6).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track17
	db 241
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 49
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track18
	db 237
	db 4	; New Instrument (4).
	db 3	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 173
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 173
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track19
	db 242
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 118
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 118
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 114
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 118
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 118
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 114
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track20
	db 235
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 171
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 171
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 171
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 171
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 171
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 171
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 171
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 171
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 171
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 171
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 171
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 171
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 171
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 171
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 171
	db 7	; New Instrument (7).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track21
	db 239
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 114
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 107
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 114
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 114
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 107
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 114
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track22
	db 235
	db 4	; New Instrument (4).
	db 3	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 147
	db 8	; New Instrument (8).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 171
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 147
	db 8	; New Instrument (8).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 171
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 147
	db 8	; New Instrument (8).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 171
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 147
	db 8	; New Instrument (8).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track23
	db 237
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 173
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 173
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 173
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 173
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 173
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 173
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 173
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 173
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 173
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 173
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 173
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 173
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 173
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 173
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 173
	db 7	; New Instrument (7).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track24
	db 241
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 116
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 109
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 116
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 113
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 116
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 109
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 116
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 113
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track25
	db 237
	db 4	; New Instrument (4).
	db 3	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 149
	db 8	; New Instrument (8).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 149
	db 8	; New Instrument (8).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 149
	db 8	; New Instrument (8).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 149
	db 8	; New Instrument (8).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track26
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 239
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 124	; No note, but effects.
	db 9	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 52
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track27
	db 239
	db 4	; New Instrument (4).
	db 6	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 151
	db 8	; New Instrument (8).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 151
	db 8	; New Instrument (8).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 151
	db 8	; New Instrument (8).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 175
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 151
	db 8	; New Instrument (8).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track28
	db 239
	db 3	; New Instrument (3).
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 175
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 175
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 175
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 175
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 175
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 175
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 175
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 175
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 175
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 175
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 175
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 175
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 175
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 175
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 175
	db 7	; New Instrument (7).
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track29
	db 246
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 9	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track30
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 239
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 124	; No note, but effects.
	db 13	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 54
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track31
	db 244
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 60	; Waits for 1 line.

	db 52
	db 61, 8	; Waits for 9 lines.

	db 124	; No note, but effects.
	db 10	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track32
	db 239
	db 1	; New Instrument (1).
	db 5	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 118
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 111
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 113
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 113
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 114
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track33
	db 235
	db 1	; New Instrument (1).
	db 5	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 60	; Waits for 1 line.

	db 107
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


music__Subsong0_Track34
	db 241
	db 1	; New Instrument (1).
	db 5	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 52
	db 60	; Waits for 1 line.

	db 109
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 113
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


; The speed tracks
music__Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
music__Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

music__Subsong0_DisarkByteRegionEnd0
