backgroundcolor = 34:32:30
keywordcolor = $62:$57:$68 
builtinfunctioncolor = $5f:$87:$5f
constantscolor = $43:$bd:$63
addresscolor = $78:$82:$4b
numberscolor = $bb:$77:$44
symbolscolor = $c9:$a5:$54
quotationcolor = 50:140:250
commentcolor = $d7:$c4:$83
textcolor = $F3:$00:$43
#currentline = 120:20:80
currentline = 70:50:20
linenumbersbackground = 15:10:25 
cyclesbackground = 25:20:35
linenumbers = 100:60:180
cycles = 150:100:120



